### ISSUE TITLE
Updates for Latest Shoutem Version

### ISSUE THREAD

**Issue by brandecho** [Kumulos/KumulosShoutemExtension#1]
Hello
Any idea on when there will be an update for the latest version of Shoutem?

**Comment by cgwyllie** [comment]
Hi @brandecho,

We are currently working on an update for the latest platform version, and expect it to be ready soon. We'll update the issue once this is available.

If you have any further specific questions, please don't hesitate to reach out to support@kumulos.com.

Kind regards,
  Chris

**Comment by brandecho** [comment]
Thank you @cgwyllie !

**Comment by cgwyllie** [comment]
@brandecho the Kumulos Shoutem Extension 2.1.3 was just published which now supports the Shoutem Platform version 2.

If you have any further questions, please contact support, we'd be happy to help.

**Comment by brandecho** [comment]
@cgwyllie Thank you. Can we simply modify the build.gradle file to include your new In App messaging SDK?

**Comment by cgwyllie** [comment]
Hi @brandecho, we do not currently have an ETA for in-app messaging for Shoutem although it is in the backlog.

The integration may be a little more involved than updating the base SDK version, as opt-in would need given as part of the configuration, and for iOS there would need to be more integration of the push notification handlers.

If you have any further questions about this, please contact your account manager who would be happy to discuss.
